language: cpp
compiler: gcc
install:
  - sudo apt-get install tcl-dev
  - sudo apt-get install libboost-all-dev
  - sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper -y
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update
  - sudo apt-get install qt-sdk libqt5svg5-dev qttools5-dev -y
  
script:
    - git clean -dfx
    - qmake Gun/Gun.pro
    - cd Gun
    - make -j2
    - mkdir vera++
    - cd vera++
    - git init
    - git clone https://bitbucket.org/verateam/vera.git
    - cd vera
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - sudo make install
    - vera++ --root . -R get_all_subDirs *
